[package]
name = "climake"
description = "A simple CLI generator using structures with no dependancies."
repository = "https://gitlab.com/pleasepm/climake"
readme = "README.md"
license = "MIT"
version = "0.1.2"
authors = ["Owez <owez@scalist.net>"]
edition = "2018"

[dependencies]
